// Package techdocs exports ADP-generated documentation as MkDocs source trees
// that the Backstage TechDocs external builder can build and serve.
//
// It does not build or upload anything itself: it produces, per Backstage
// entity, a standard MkDocs source layout (mkdocs.yml + docs/) that
// `techdocs-cli generate` consumes and `techdocs-cli publish` uploads to your
// TechDocs storage, keyed by the entity triplet namespace/kind/name.
package techdocs

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

// Doc is a generated ADP document to publish. Content is Markdown.
type Doc struct {
	ID        string
	SessionID string
	Category  string
	Title     string
	Content   string
	CreatedAt time.Time
}

// Service identifies a Backstage entity target for an ADP service.
type Service struct {
	ID        string
	Name      string // human name; the entity Name becomes SanitizeName(Name)
	Namespace string // default "default"
	Kind      string // default "Component"
}

// EntitySite is the set of docs for one Backstage entity (namespace/kind/name).
type EntitySite struct {
	Namespace string
	Kind      string
	Name      string
	Title     string // human title (service name) used for site_name
	Docs      []Doc
}

// EntityRef returns the techdocs-cli --entity triplet (namespace/kind/name).
func (s EntitySite) EntityRef() string {
	return fmt.Sprintf("%s/%s/%s", s.Namespace, s.Kind, s.Name)
}

var (
	categoryTitles = map[string]string{
		"session_summary": "Session summaries",
		"risk_report":     "Risk reports",
		"pattern_report":  "Pattern reports",
	}
	categoryOrder = []string{"session_summary", "risk_report", "pattern_report"}

	slugInvalid = regexp.MustCompile(`[^a-z0-9]+`)
	nameInvalid = regexp.MustCompile(`[^a-z0-9-]`)
	nameDashes  = regexp.MustCompile(`-+`)
)

// SanitizeName mirrors the Backstage AdpEntityProvider entity naming so the
// published TechDocs entity key matches the catalog entity: lowercase,
// non-alphanumeric to dashes, collapsed, trimmed, max 63 chars.
func SanitizeName(name string) string {
	s := strings.ToLower(name)
	s = nameInvalid.ReplaceAllString(s, "-")
	s = nameDashes.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	if len(s) > 63 {
		s = strings.Trim(s[:63], "-")
	}
	return s
}

// GroupDocsByEntity assigns docs to per-service entity sites. sessionServices
// maps a session ID to the service IDs it was scoped to (from the session's
// service_scope); each doc is placed on every matching service's site. The
// result preserves the input service order and is otherwise deterministic.
func GroupDocsByEntity(services []Service, sessionServices map[string][]string, docs []Doc) []EntitySite {
	sites := make(map[string]*EntitySite, len(services))
	order := make([]string, 0, len(services))
	for _, svc := range services {
		ns := svc.Namespace
		if ns == "" {
			ns = "default"
		}
		kind := svc.Kind
		if kind == "" {
			kind = "Component"
		}
		sites[svc.ID] = &EntitySite{
			Namespace: ns,
			Kind:      kind,
			Name:      SanitizeName(svc.Name),
			Title:     svc.Name,
		}
		order = append(order, svc.ID)
	}

	for _, d := range docs {
		for _, sid := range sessionServices[d.SessionID] {
			if site, ok := sites[sid]; ok {
				site.Docs = append(site.Docs, d)
			}
		}
	}

	out := make([]EntitySite, 0, len(order))
	for _, id := range order {
		out = append(out, *sites[id])
	}
	return out
}

// BuildSite renders the MkDocs source tree for an entity as a map of relative
// file path -> file content. Deterministic for a given input.
func BuildSite(site EntitySite) map[string]string {
	byCat := map[string][]Doc{}
	for _, d := range site.Docs {
		byCat[d.Category] = append(byCat[d.Category], d)
	}
	for cat := range byCat {
		ds := byCat[cat]
		sort.SliceStable(ds, func(i, j int) bool {
			if !ds[i].CreatedAt.Equal(ds[j].CreatedAt) {
				return ds[i].CreatedAt.After(ds[j].CreatedAt)
			}
			return ds[i].ID < ds[j].ID
		})
		byCat[cat] = ds
	}

	siteTitle := site.Title
	if siteTitle == "" {
		siteTitle = site.Name
	}

	var nav strings.Builder
	nav.WriteString("nav:\n")
	nav.WriteString("  - Overview: index.md\n")

	var idx strings.Builder
	idx.WriteString(fmt.Sprintf("# %s — agent governance docs\n\n", siteTitle))
	idx.WriteString("Auto-generated by the ADP documentation engine.\n\n")
	if len(site.Docs) == 0 {
		idx.WriteString("_No documents have been generated for this service yet._\n")
	}

	files := map[string]string{}
	usedSlugs := map[string]bool{}
	for _, cat := range orderedCategories(byCat) {
		ds := byCat[cat]
		if len(ds) == 0 {
			continue
		}
		catTitle := categoryTitles[cat]
		if catTitle == "" {
			catTitle = titleizeCategory(cat)
		}
		nav.WriteString(fmt.Sprintf("  - %s:\n", yamlScalar(catTitle)))
		idx.WriteString(fmt.Sprintf("## %s\n\n", catTitle))
		for _, d := range ds {
			base := slugify(d.Title)
			slug := base
			for n := 2; usedSlugs[cat+"/"+slug]; n++ {
				slug = fmt.Sprintf("%s-%d", base, n)
			}
			usedSlugs[cat+"/"+slug] = true

			rel := fmt.Sprintf("%s/%s.md", cat, slug)
			docTitle := nonEmpty(d.Title, "Untitled")
			nav.WriteString(fmt.Sprintf("      - %s: %s\n", yamlScalar(docTitle), rel))
			idx.WriteString(fmt.Sprintf("- [%s](%s)\n", docTitle, rel))
			files["docs/"+rel] = renderDocPage(d)
		}
		idx.WriteString("\n")
	}

	files["docs/index.md"] = idx.String()
	files["mkdocs.yml"] = renderMkdocsYml(siteTitle, nav.String())
	return files
}

// WriteSite writes BuildSite output under rootDir/<namespace>/<kind>/<name> and
// returns that directory.
func WriteSite(rootDir string, site EntitySite) (string, error) {
	dir := filepath.Join(rootDir, site.Namespace, site.Kind, site.Name)
	for rel, content := range BuildSite(site) {
		p := filepath.Join(dir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return "", err
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			return "", err
		}
	}
	return dir, nil
}

func renderMkdocsYml(siteTitle, nav string) string {
	var b strings.Builder
	b.WriteString("site_name: " + yamlScalar(siteTitle+" — ADP governance") + "\n")
	b.WriteString("site_description: " + yamlScalar("Agent governance documentation generated by ADP") + "\n")
	b.WriteString("plugins:\n  - techdocs-core\n")
	b.WriteString(nav)
	return b.String()
}

func renderDocPage(d Doc) string {
	var b strings.Builder
	b.WriteString("# " + nonEmpty(d.Title, "Untitled") + "\n\n")
	var meta []string
	if d.SessionID != "" {
		meta = append(meta, "Session: `"+d.SessionID+"`")
	}
	if !d.CreatedAt.IsZero() {
		meta = append(meta, "Generated: "+d.CreatedAt.UTC().Format(time.RFC3339))
	}
	if len(meta) > 0 {
		b.WriteString("_" + strings.Join(meta, " · ") + "_\n\n")
	}
	b.WriteString(d.Content)
	if !strings.HasSuffix(d.Content, "\n") {
		b.WriteString("\n")
	}
	return b.String()
}

func orderedCategories(byCat map[string][]Doc) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(byCat))
	for _, c := range categoryOrder {
		if _, ok := byCat[c]; ok {
			out = append(out, c)
			seen[c] = true
		}
	}
	var extra []string
	for c := range byCat {
		if !seen[c] {
			extra = append(extra, c)
		}
	}
	sort.Strings(extra)
	return append(out, extra...)
}

func slugify(s string) string {
	s = strings.ToLower(s)
	s = slugInvalid.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	if s == "" {
		return "doc"
	}
	if len(s) > 80 {
		s = strings.Trim(s[:80], "-")
	}
	return s
}

func titleizeCategory(c string) string {
	c = strings.ReplaceAll(c, "_", " ")
	if c == "" {
		return c
	}
	return strings.ToUpper(c[:1]) + c[1:]
}

func yamlScalar(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

func nonEmpty(s, def string) string {
	if s == "" {
		return def
	}
	return s
}
